id: video2
uri: /video
# This limits fps to the fps of the source (only really makes sense with video files, if a camera shall be simulated)
use_source_fps: True
reconnect_backoff_time: 1
log_level: DEBUG
redis:
  host: redis
  port: 6379