nameOverride: ""
fullnameOverride: ""

# extraImagePullSecrets:
#   - name: extra-pull-secret

videoSource:
  image: 
    repository: starwitorg/sae-video-source-py
    tag: 0.8.0
  configs: 
  - id: video1
    uri: 'uri'
    maxFps: 0
    jpegEncode: "True"
    logLevel: DEBUG

objectDetector:
  image:
    repository: starwitorg/sae-object-detector
    tag: 0.7.1
  config:
    model:
      size: "n"
      device: cpu
    inferenceSize: [ 640, 640 ]
    classes: [ 2 ]
    logLevel: DEBUG
    redis:
      streamIds:
        - video1

objectTracker:
  image:
    repository: starwitorg/sae-object-tracker
    tag: 1.0.0
  logLevel: DEBUG
  needsGpu: False
  streamIds:
    - video1
  config:
    tracker_algorithm: OCSORT
    tracker_config:
      det_thresh: 0.2
      max_age: 30
      min_hits: 3
      asso_threshold: 0.3
      delta_t: 3
      asso_func: 'iou'
      inertia: 0.2
      use_byte: False

databaseWriter:
  image:
    repository: starwitorg/sae-database-writer
    tag: 0.5.1
  config:
    redisStreamIds:
      - video1
    db:
      jdbcUrl: jdbc:postgresql://host:port/
      schema: schema
      username: username
      password: password
      hypertable: tablename

redis:
  architecture: standalone
  auth:
    enabled: false
  commonConfiguration: |-
    save ""
    appendonly no
  master:
    persistence:
      enabled: false
  metrics:
    enabled: true

prometheus:
  alertmanager:
    enabled: false
  server:
    service:
      type: ClusterIP
    scrapeInterval: 10s
    evaluationInterval: 10s
    extraScrapeConfigs:
      - job_name: redis_exporter
        static_configs:
          - targets: ['{{ include "sae.redisMetricsServiceName" $ }}:9121']
      - job_name: node_exporter
        static_configs:
          - targets: ['{{ include "sae.nodeExporterServiceName" $ }}:9100']
      - job_name: sae_pods
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              own_namespace: true
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_sae_starwit_de_stage]
            action: keep
            regex: (video-source|object-detector|object-tracker)
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_annotation_sae_starwit_de_stage]
            action: replace
            target_label: stage
          

grafana:
  admin:
    password: admin
  datasources:
    secretDefinition: 
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://{{ include "sae.prometheusServiceName" . }}


nodeexporter:
  enabled: true